### ISSUE TITLE
ImmichFrame don't start on Unraid

### ISSUE THREAD

**Issue by PrzemekSkw** [immichFrame/ImmichFrame#151]
### Version

ghcr.io/immichframe/immichframe:latest

### Deployment Method

docker

### Description

I install last docker template on unraid. I change port to 8787.
I create Settings.json and container won't start.

### Reproduction

try local IP and external domain

### Expectations

just start and works

### Configuration

```xml
"ImmichServerUrl": "https://.................ddns.net",
"ApiKey": "ei1..................................driQRA",
"Albums": ["2ef34871-6b82-4cdc-9969-04a8effddf80"],
```
```


### Logs


```shell
Unhandled exception. ImmichFrame.Core.Exceptions.SettingsNotValidException: Problem with parsing the settings: ':' is invalid after a single JSON value. Expected end of data. LineNumber: 1 | BytePositionInLine: 17.
 ---> System.Text.Json.JsonReaderException: ':' is invalid after a single JSON value. Expected end of data. LineNumber: 1 | BytePositionInLine: 17.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenOrRollback(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedArrayPoolBytes, PooledByteBufferWriter extraPooledByteBufferWriter)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 json, JsonDocumentOptions options)
   at Program.<Main>$(String[] args) in /source/ImmichFrame.WebApi/Program.cs:line 26
   --- End of inner exception stack trace ---
   at Program.<Main>$(String[] args) in /source/ImmichFrame.WebApi/Program.cs:line 30
Unhandled exception. ImmichFrame.Core.Exceptions.SettingsNotValidException: Problem with parsing the settings: ':' is invalid after a single JSON value. Expected end of data. LineNumber: 1 | BytePositionInLine: 17.
 ---> System.Text.Json.JsonReaderException: ':' is invalid after a single JSON value. Expected end of data. LineNumber: 1 | BytePositionInLine: 17.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenOrRollback(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedArrayPoolBytes, PooledByteBufferWriter extraPooledByteBufferWriter)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 json, JsonDocumentOptions options)
   at Program.<Main>$(String[] args) in /source/ImmichFrame.WebApi/Program.cs:line 26
   --- End of inner exception stack trace ---
   at Program.<Main>$(String[] args) in /source/ImmichFrame.WebApi/Program.cs:line 30
/app/Config/Settings.json
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:8080
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HN76N4BBA64D", Request id "0HN76N4BBA64D:00000005": An unhandled exception was thrown by the application.
      System.InvalidOperationException: An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.
         at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)
         at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
         at ImmichFrame.Core.Api.ImmichApi.SearchRandomAsync(RandomSearchDto body, CancellationToken cancellationToken) in /source/ImmichFrame.Core/obj/immich-openapi-specsClient.cs:line 8223
         at ImmichFrame.Core.Logic.ImmichFrameLogic.GetRandomAsset() in /source/ImmichFrame.Core/Logic/ImmichFrameLogic.cs:line 318
         at ImmichFrame.Core.Logic.ImmichFrameLogic.GetNextAsset() in /source/ImmichFrame.Core/Logic/ImmichFrameLogic.cs:line 57
         at ImmichFrame.WebApi.Controllers.AssetController.GetAsset() in /source/ImmichFrame.WebApi/Controllers/AssetController.cs:line 24
         at lambda_method6(Closure, Object)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
/app/Config/Settings.json
/app/Config/Settings.json
```
```


### Pre-Submission Checklist


- [X] This is a bug report and not a feature request

- [X] I have provided all of the required information to reproduce the bug (config, logs, etc.)

- [X] I have checked for related issues and checked the documentation

**Comment by JW-CH** [comment]
Can you try to remove the `,` after your `"Albums": ["xxx"]` <- HERE

Not sure why this is an issue, but I think this will fix it in your case. I will make sure this will not be an issue in the future. Thanks for reporting

**Comment by JW-CH** [comment]
Also, just to be clear:

Your configuration needs to be a file called `Settings.json`. Your JSON needs to have opening and closing curly brackets.


Your settings would look something like this:
```json
{
  "ImmichServerUrl": "https://.................ddns.net",
  "ApiKey": "ei1..................................driQRA",
  "Albums": [
    "2ef34871-6b82-4cdc-9969-04a8effddf80"
  ]
}
```

**Comment by PrzemekSkw** [comment]
> Also, just to be clear:
> 
> Your configuration needs to be a file called `Settings.json`. Your JSON needs to have opening and closing curly brackets.
> 
> Your settings would look something like this:
> 
> ```json
> {
>   "ImmichServerUrl": "https://.................ddns.net",
>   "ApiKey": "ei1..................................driQRA",
>   "Albums": [
>     "2ef34871-6b82-4cdc-9969-04a8effddf80"
>   ]
> }
> ```
Thank that works. I can't find any Settings.json example here or in config folder.
Meybe add one on main page.
Regards.

**Comment by JW-CH** [comment]
> > Also, just to be clear:
> > Your configuration needs to be a file called `Settings.json`. Your JSON needs to have opening and closing curly brackets.
> > Your settings would look something like this:
> > ```json
> > {
> >   "ImmichServerUrl": "https://.................ddns.net",
> >   "ApiKey": "ei1..................................driQRA",
> >   "Albums": [
> >     "2ef34871-6b82-4cdc-9969-04a8effddf80"
> >   ]
> > }
> > ```
> 
> Thank that works. I can't find any Settings.json example here or in config folder. Meybe add one on main page. Regards.

There is one, but it is maybe a bit nested:
https://github.com/immichFrame/ImmichFrame/blob/main/ImmichFrame/Settings.example.json

It might be a good idea to link it from the README.
