### ISSUE TITLE
500 with from /api/Asset

### ISSUE THREAD

**Issue by rtprio** [immichFrame/ImmichFrame#162]
### Version

ghcr.io/immichframe/immichframe:v1.0.13.0

### Deployment Method

web

### Description

I copied the same config as the android version, which works fine.

This could be a configuration error. If that's the case then the bug is "undecipherable stack trace / lack of error message".

### Reproduction

Following the instructions, copied `Settings.example.json` and set url, key and one album uuid.
 

### Expectations

same album to load as the android version

### Configuration

```xml
{
  "ImmichServerUrl": "https://photos.example.org",
  "ApiKey": "W3oRUVuRf93XİN1example9djcUAFfYeCHI",
  "ImageStretch": "Uniform",
  "Margin": "0,0,0,0",
  "Interval": 10,
  "TransitionDuration": 2,
  "DownloadImages": false,
  "ShowMemories": false,
  "RenewImagesDuration": 30,
  "Albums": [ "4d17dc4f-4665-4d9f-a9de-d11cab72c0c0" ],
  "RefreshAlbumPeopleInterval": 12,
  "ShowClock": false,
  "ClockFontSize": 36,
  "ClockFormat": "HH:mm:ss",
  "ShowPhotoDate": true,
  "PhotoDateFontSize": 24,
  "PhotoDateFormat": "yyyy-MM-dd",
  "ShowImageDesc": true,
  "ImageDescFontSize": 24,
  "ShowImageLocation": true,
  "ImageLocationFormat": "City,State,Country",
  "ImageLocationFontSize": 16,
  "FontColor": "#FF5733",
  "WeatherApiKey": "",
  "ShowWeatherDescription": true,
  "WeatherFontSize": 24,
  "UnitSystem": "imperial",
  "WeatherLatLong": "",
  "Language": "en",
  "UnattendedMode": false
}
```

### Logs

```shell
Attaching to immichframe
immichframe  | /app/Config/Settings.json
immichframe  | info: Microsoft.Hosting.Lifetime[14]
immichframe  |       Now listening on: http://[::]:8080
immichframe  | info: Microsoft.Hosting.Lifetime[0]
immichframe  |       Application started. Press Ctrl+C to shut down.
immichframe  | info: Microsoft.Hosting.Lifetime[0]
immichframe  |       Hosting environment: Production
immichframe  | info: Microsoft.Hosting.Lifetime[0]
immichframe  |       Content root path: /app
immichframe  | fail: Microsoft.AspNetCore.Server.Kestrel[13]
immichframe  |       Connection id "0HN7B0MFTIEJ8", Request id "0HN7B0MFTIEJ8:00000007": An unhandled exception was thrown by the application.
immichframe  |       System.Net.Http.HttpRequestException: Request headers must contain only ASCII characters.
immichframe  |          at System.Net.Http.HttpConnection.<WriteString>g__ThrowForInvalidCharEncoding|56_0()
immichframe  |          at System.Net.Http.HttpConnection.WriteString(String s, Encoding encoding)
immichframe  |          at System.Net.Http.HttpConnection.WriteHeaderCollection(HttpHeaders headers, String cookiesFromContainer)
immichframe  |          at System.Net.Http.HttpConnection.WriteHeaders(HttpRequestMessage request, HttpMethod normalizedMethod)
immichframe  |          at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
immichframe  |          at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
immichframe  |          at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
immichframe  |          at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
immichframe  |          at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
immichframe  |          at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
immichframe  |          at ImmichFrame.Core.Api.ImmichApi.GetAlbumInfoAsync(Guid id, String key, Nullable`1 withoutAssets, CancellationToken cancellationToken) in /source/ImmichFrame.Core/obj/immich-openapi-specsClient.cs:line 1361
immichframe  |          at ImmichFrame.Core.Logic.ImmichFrameLogic.GetAlbumAssets(Guid albumId, ImmichApi immichApi) in /source/ImmichFrame.Core/Logic/ImmichFrameLogic.cs:line 190
immichframe  |          at ImmichFrame.Core.Logic.ImmichFrameLogic.GetAlbumAssets() in /source/ImmichFrame.Core/Logic/ImmichFrameLogic.cs:line 210
immichframe  |          at ImmichFrame.Core.Logic.ImmichFrameLogic.GetFilteredAssetIds() in /source/ImmichFrame.Core/Logic/ImmichFrameLogic.cs:line 128
immichframe  |          at ImmichFrame.Core.Logic.ImmichFrameLogic.GetNextAsset() in /source/ImmichFrame.Core/Logic/ImmichFrameLogic.cs:line 52
immichframe  |          at ImmichFrame.WebApi.Controllers.AssetController.GetAsset() in /source/ImmichFrame.WebApi/Controllers/AssetController.cs:line 24
immichframe  |          at lambda_method6(Closure, Object)
immichframe  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
immichframe  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
immichframe  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
immichframe  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
immichframe  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
immichframe  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
immichframe  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
immichframe  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
immichframe  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
immichframe  |          at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
immichframe  |          at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
immichframe  |          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

### Pre-Submission Checklist

- [X] This is a bug report and not a feature request

- [X] I have provided all of the required information to reproduce the bug (config, logs, etc.)

- [X] I have checked for related issues and checked the documentation

**Comment by rtprio** [comment]
on a whim I tried another API key, and it seems to work.

so perhaps that we can test the endpoint or look for a 401 from immich before trying to continue?

**Comment by JW-CH** [comment]
> on a whim I tried another API key, and it seems to work.
> 
> so perhaps that we can test the endpoint or look for a 401 from immich before trying to continue?

so you are saying that the api-key was the issue. I don't fully understand yet

**Comment by JW-CH** [comment]
Closing this, please reopen if not resolved.
