### ISSUE TITLE
No assets were found!

### ISSUE THREAD

**Issue by zycker** [immichFrame/ImmichFrame#244]
### Version

v1.0.21.0

### Deployment Method

Docker

### Description

I can access the web page but it only show me : 
![image](https://github.com/user-attachments/assets/688a66d8-8687-45de-97ca-a63b44ee5690)

I've created temporary album with the names ALBUM1 and ALBUM2. Both Immich and ImmichFrame have been restared.

### Reproduction

docker compose up -d

### Configuration

```xml
docker-compose.yml :
name: immichframe
services:
  immichframe:
    container_name: immichframe
    image: ghcr.io/immichframe/immichframe:latest
    restart: on-failure
    # volumes:
    #   - PATH/TO/CONFIG:/app/Config
    ports:
      - "8085:8080"
    env_file:
      - .env
    environment:
      TZ: "Europe/Berlin"


.env :

ImmichServerUrl=http://192.168.1.5:2283
ApiKey=QbW8YPBajhYetc.
Margin=0,0,0,0
Interval=10
TransitionDuration=2
DownloadImages=false
ShowMemories=false
ImagesFromDays=
ImagesFromDate=
ImagesUntilDate=
RenewImagesDuration=30
Albums=ALBUM1,ALBUM2
ExcludedAlbums=ALBUM3,ALBUM4
People=PERSON1,PERSON2
Webcalendars=https://calendar.mycalendar.com/basic.ics,webcal://calendar.mycalendar.com/basic.ics
RefreshAlbumPeopleInterval=12
ShowClock=true
ClockFormat=HH:mm:ss
ShowPhotoDate=true
PhotoDateFormat=yyyy-MM-dd
ShowImageDesc=true
ShowPeopleDesc=true
ShowImageLocation=true
ImageLocationFormat=City,State,Country
PrimaryColor=#FF5733
SecondaryColor=#000000
Style=none
BaseFontSize=17px
WeatherApiKey=
ShowWeatherDescription=true
UnitSystem=imperial
WeatherLatLong=
Language=en
ImageZoom=true
Layout=splitview
Webhook=
```

### Logs

```shell
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
         at lambda_method10(Closure, IServiceProvider, Object[])
         at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass6_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:8080
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HN97S1JT55C3", Request id "0HN97S1JT55C3:00000003": An unhandled exception was thrown by the application.
      ImmichFrame.Core.Exceptions.SettingsNotValidException: Problem with parsing the settings: Unrecognized Guid format.
       ---> System.FormatException: Unrecognized Guid format.
         at System.Guid.GuidResult.SetFailure(ParseFailure failureKind)
         at System.Guid.TryParseGuid(ReadOnlySpan`1 guidString, GuidResult& result)
         at System.Guid..ctor(String g)
         at ImmichFrame.WebApi.Helpers.SettingsExtensions.<>c.<SetValue>b__2_0(String x) in /source/ImmichFrame.WebApi/Helpers/SettingsExtensonMethods.cs:line 28
         at System.Linq.Enumerable.SelectArrayIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
         at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
         at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
         at ImmichFrame.WebApi.Helpers.SettingsExtensions.SetValue(Object settings, PropertyInfo prop, String value) in /source/ImmichFrame.WebApi/Helpers/SettingsExtensonMethods.cs:line 28
         at ImmichFrame.WebApi.Helpers.SettingsExtensions.SetValue(ServerSettings s, PropertyInfo prop, String value) in /source/ImmichFrame.WebApi/Helpers/SettingsExtensonMethods.cs:line 10
         at ImmichFrame.WebApi.Models.ServerSettings..ctor() in /source/ImmichFrame.WebApi/Models/ServerSettings.cs:line 9
         --- End of inner exception stack trace ---
         at ImmichFrame.WebApi.Models.ServerSettings..ctor() in /source/ImmichFrame.WebApi/Models/ServerSettings.cs:line 50
         at Program.<>c__DisplayClass0_0.<<Main>$>b__0(IServiceProvider srv) in /source/ImmichFrame.WebApi/Program.cs:line 38
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
         at lambda_method10(Closure, IServiceProvider, Object[])
         at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass6_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HN97S1JT55C4", Request id "0HN97S1JT55C4:00000003": An unhandled exception was thrown by the application.
      ImmichFrame.Core.Exceptions.SettingsNotValidException: Problem with parsing the settings: Unrecognized Guid format.
       ---> System.FormatException: Unrecognized Guid format.
         at System.Guid.GuidResult.SetFailure(ParseFailure failureKind)
         at System.Guid.TryParseGuid(ReadOnlySpan`1 guidString, GuidResult& result)
         at System.Guid..ctor(String g)
         at ImmichFrame.WebApi.Helpers.SettingsExtensions.<>c.<SetValue>b__2_0(String x) in /source/ImmichFrame.WebApi/Helpers/SettingsExtensonMethods.cs:line 28
         at System.Linq.Enumerable.SelectArrayIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
         at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
         at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
         at ImmichFrame.WebApi.Helpers.SettingsExtensions.SetValue(Object settings, PropertyInfo prop, String value) in /source/ImmichFrame.WebApi/Helpers/SettingsExtensonMethods.cs:line 28
         at ImmichFrame.WebApi.Helpers.SettingsExtensions.SetValue(ServerSettings s, PropertyInfo prop, String value) in /source/ImmichFrame.WebApi/Helpers/SettingsExtensonMethods.cs:line 10
         at ImmichFrame.WebApi.Models.ServerSettings..ctor() in /source/ImmichFrame.WebApi/Models/ServerSettings.cs:line 9
         --- End of inner exception stack trace ---
         at ImmichFrame.WebApi.Models.ServerSettings..ctor() in /source/ImmichFrame.WebApi/Models/ServerSettings.cs:line 50
         at Program.<>c__DisplayClass0_0.<<Main>$>b__0(IServiceProvider srv) in /source/ImmichFrame.WebApi/Program.cs:line 38
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
         at lambda_method10(Closure, IServiceProvider, Object[])
         at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass6_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

### Pre-Submission Checklist

- [X] This is a bug report and not a feature request

- [X] I have provided all of the required information to reproduce the bug (config, logs, etc.)

- [X] I have checked for related issues and checked the documentation

**Comment by 3rob3** [comment]
You need to use UUID's for albums and people, not their names. The UUID (32 hexadecimal characters with four hyphens: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX) can be found by going into the album on a browser and looking at the URL.
Also, you need to comment out anything your not using (Person, Calender, etc).

**Comment by zycker** [comment]
Indeed, thank you for your quick answer. It works now.
